// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.

#pragma once 
#include <windows.h>
#include <ntverp.h>

#define VER_FILETYPE              VFT_APP
#define VER_FILESUBTYPE           VFT2_UNKNOWN
#define VER_FILEDESCRIPTION_STR   "MUIAppSample"
#define VER_INTERNALNAME_STR      "MUIAPPSAMPLE"
#define VER_ORIGINALFILENAME_STR  "MUIAppSample.exe"

#include "common.ver"
