//
// Resource header file generated by CTRPP tool, contains STRINGID definition.
//
#define IDS_PerflibV2SampleProvider_00035         35
#define IDS_PerflibV2SampleProvider_00033         33
#define IDS_PerflibV2SampleProvider_00034         34
#define IDS_PerflibV2SampleProvider_00031         31
#define IDS_PerflibV2SampleProvider_00029         29
#define IDS_PerflibV2SampleProvider_00030         30
#define IDS_PerflibV2SampleProvider_00027         27
#define IDS_PerflibV2SampleProvider_00025         25
#define IDS_PerflibV2SampleProvider_00026         26
#define IDS_PerflibV2SampleProvider_00023         23
#define IDS_PerflibV2SampleProvider_00021         21
#define IDS_PerflibV2SampleProvider_00022         22
#define IDS_PerflibV2SampleProvider_00019         19
#define IDS_PerflibV2SampleProvider_00017         17
#define IDS_PerflibV2SampleProvider_00018         18
#define IDS_PerflibV2SampleProvider_00015         15
#define IDS_PerflibV2SampleProvider_00013         13
#define IDS_PerflibV2SampleProvider_00014         14
#define IDS_PerflibV2SampleProvider_00011         11
#define IDS_PerflibV2SampleProvider_00009          9
#define IDS_PerflibV2SampleProvider_00010         10
#define IDS_PerflibV2SampleProvider_00007          7
#define IDS_PerflibV2SampleProvider_00005          5
#define IDS_PerflibV2SampleProvider_00006          6
#define IDS_PerflibV2SampleProvider_00003          3
#define IDS_PerflibV2SampleProvider_00001          1
#define IDS_PerflibV2SampleProvider_00002          2

