//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="OCSPSample.Properties.Resources.get_ResourceManager():System.Resources.ResourceMa" +
    "nager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="OCSPSample.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="OCSPSample.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Voi" +
    "d")]

namespace OCSPSample.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCSPSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply changes to the responder..
        /// </summary>
        internal static string strApplyChangesFailed {
            get {
                return ResourceManager.GetString("strApplyChangesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder Connected..
        /// </summary>
        internal static string strConnected {
            get {
                return ResourceManager.GetString("strConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Responder:.
        /// </summary>
        internal static string strConnecting {
            get {
                return ResourceManager.GetString("strConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder cannot be connected..
        /// </summary>
        internal static string strNotConnected {
            get {
                return ResourceManager.GetString("strNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has been applied to the Responder..
        /// </summary>
        internal static string strPropertyApplied {
            get {
                return ResourceManager.GetString("strPropertyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property created..
        /// </summary>
        internal static string strPropertyCreated {
            get {
                return ResourceManager.GetString("strPropertyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property does not exist..
        /// </summary>
        internal static string strPropertyDoesNotExist {
            get {
                return ResourceManager.GetString("strPropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property could not be created..
        /// </summary>
        internal static string strPropertyNotCreated {
            get {
                return ResourceManager.GetString("strPropertyNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property could not be retrieved.Will attempt to create it..
        /// </summary>
        internal static string strPropertyNotRetrieved {
            get {
                return ResourceManager.GetString("strPropertyNotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property will be set to the following value:.
        /// </summary>
        internal static string strPropertySet {
            get {
                return ResourceManager.GetString("strPropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value is the following:.
        /// </summary>
        internal static string strPropertyValue {
            get {
                return ResourceManager.GetString("strPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved the revocation configuration..
        /// </summary>
        internal static string strRevCfgRetrieved {
            get {
                return ResourceManager.GetString("strRevCfgRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the revocation configuration..
        /// </summary>
        internal static string strRevCfgRetrieveFailed {
            get {
                return ResourceManager.GetString("strRevCfgRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the following revocation configuration:.
        /// </summary>
        internal static string strRevCfgRetrieving {
            get {
                return ResourceManager.GetString("strRevCfgRetrieving", resourceCulture);
            }
        }
    }
}
