#----- Include the PSDK's WIN32.MAK to pick up defines ------------------------------------
!include <win32.mak>

!IF "$(TARGETOS)" == "WINNT"

!include <win32.mak>

all: $(OUTDIR)\prperf.exe

#----- If OUTDIR does not exist, then create directory
$(OUTDIR) :
    if not exist "$(OUTDIR)/$(NULL)" mkdir $(OUTDIR)

#--------------------- EXE ---------------------------------------------------------------
#PLEASE REFER TO WIN32.MAK for the different Linker options WIN32.MAK provides

# Build rule for EXE


SOURCE=.\prperf.c

$(OUTDIR)\prperf.obj : $(SOURCE) $(OUTDIR)
    $(cc) $(cdebug) $(cflags) /WX /W3 /Fo"$(OUTDIR)\\" /Fd"$(OUTDIR)\\" $(SOURCE)

$(OUTDIR)\prperf.exe:  $(OUTDIR) $(OUTDIR)\prperf.obj
	$(link) $(ldebug) $(conflags) /PDB:$(OUTDIR)\prperf.pdb -out:$(OUTDIR)\prperf.exe $(OUTDIR)\prperf.obj $(conlibs)

clean:
	$(CLEANUP)

!ELSE
!MESSAGE Sorry this sample only builds for the Windows NT Platform
!ENDIF

